Repository letehaha/budget-tracker-fe, pull requests merged in 2023-07, with the labels that each got.

#195 feat/let user remove custom exchange rate
  .eslintrc.js
  package.json
  src/api/currencies.ts
  src/components/fields/input-field.vue
  src/js/records/models/exchange-rate.record.ts
  src/pages/settings/tabs/currencies/edit-currency.vue
  src/pages/settings/tabs/currencies/list.vue
  src/pages/settings/tabs/currencies/types.ts
Labels: type::enhancement

#203 fix: Stabilize e2e tests
  cypress/e2e/SignIn.cy.ts
Labels: repo: frontend, ci/cd

#205 fix: CategorySelectField broken selection
  src/components/fields/category-select-field.vue
  src/components/fields/components/field-label.vue
Labels: type::bug
